


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."rls_auto_enable"() RETURNS "event_trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$$;


ALTER FUNCTION "public"."rls_auto_enable"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Games" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text"
);


ALTER TABLE "public"."Games" OWNER TO "postgres";


ALTER TABLE "public"."Games" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Games_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."HealingLedger" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "taskId" bigint,
    "healedTaskId" bigint,
    "userId" bigint
);


ALTER TABLE "public"."HealingLedger" OWNER TO "postgres";


COMMENT ON TABLE "public"."HealingLedger" IS 'History of the healing tasks';



ALTER TABLE "public"."HealingLedger" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."HealingLedger_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Item" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "price" smallint,
    "itemEffectId" bigint
);


ALTER TABLE "public"."Item" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."ItemEffect" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "description" "text"
);


ALTER TABLE "public"."ItemEffect" OWNER TO "postgres";


ALTER TABLE "public"."ItemEffect" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ItemEffect_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."Item" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Item_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Locations" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "gameId" bigint
);


ALTER TABLE "public"."Locations" OWNER TO "postgres";


ALTER TABLE "public"."Locations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Locations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Shop" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "itemId" bigint,
    "targetId" bigint,
    "userId" bigint
);


ALTER TABLE "public"."Shop" OWNER TO "postgres";


COMMENT ON TABLE "public"."Shop" IS 'Ledger of the purchased shop items';



ALTER TABLE "public"."Shop" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Shop_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Students" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "group" "text",
    "klass" "text",
    "teamId" bigint
);


ALTER TABLE "public"."Students" OWNER TO "postgres";


ALTER TABLE "public"."Students" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Students_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Tasks" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "text" "text",
    "solution" "text",
    "isMiniBoss" boolean,
    "gameId" bigint,
    "locationId" bigint
);


ALTER TABLE "public"."Tasks" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."TasksLedger" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "taskId" bigint NOT NULL,
    "userId" bigint,
    "isSuccess" boolean
);


ALTER TABLE "public"."TasksLedger" OWNER TO "postgres";


COMMENT ON TABLE "public"."TasksLedger" IS 'Store all the task actions';



ALTER TABLE "public"."TasksLedger" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."TasksLedger_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."Tasks" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Tasks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."TeamAssignment" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "baseTeamCounter" bigint
);


ALTER TABLE "public"."TeamAssignment" OWNER TO "postgres";


ALTER TABLE "public"."TeamAssignment" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."TeamAssignment_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Teams" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "teamAssignmentId" bigint
);


ALTER TABLE "public"."Teams" OWNER TO "postgres";


ALTER TABLE "public"."Teams" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Teams_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."Games"
    ADD CONSTRAINT "Games_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."HealingLedger"
    ADD CONSTRAINT "HealingLedger_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ItemEffect"
    ADD CONSTRAINT "ItemEffect_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Item"
    ADD CONSTRAINT "Item_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Locations"
    ADD CONSTRAINT "Locations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Shop"
    ADD CONSTRAINT "Shop_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Students"
    ADD CONSTRAINT "Students_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."TasksLedger"
    ADD CONSTRAINT "TasksLedger_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Tasks"
    ADD CONSTRAINT "Tasks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."TeamAssignment"
    ADD CONSTRAINT "TeamAssignment_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Teams"
    ADD CONSTRAINT "Teams_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."HealingLedger"
    ADD CONSTRAINT "HealingLedger_healedTaskId_fkey" FOREIGN KEY ("healedTaskId") REFERENCES "public"."Tasks"("id");



ALTER TABLE ONLY "public"."HealingLedger"
    ADD CONSTRAINT "HealingLedger_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "public"."Tasks"("id");



ALTER TABLE ONLY "public"."Item"
    ADD CONSTRAINT "Item_itemEffectId_fkey" FOREIGN KEY ("itemEffectId") REFERENCES "public"."ItemEffect"("id");



ALTER TABLE ONLY "public"."Locations"
    ADD CONSTRAINT "Locations_gameId_fkey" FOREIGN KEY ("gameId") REFERENCES "public"."Games"("id");



ALTER TABLE ONLY "public"."Shop"
    ADD CONSTRAINT "Shop_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "public"."Item"("id");



ALTER TABLE ONLY "public"."Students"
    ADD CONSTRAINT "Students_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "public"."Teams"("id");



ALTER TABLE ONLY "public"."TasksLedger"
    ADD CONSTRAINT "TasksLedger_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "public"."Tasks"("id");



ALTER TABLE ONLY "public"."Tasks"
    ADD CONSTRAINT "Tasks_gameId_fkey" FOREIGN KEY ("gameId") REFERENCES "public"."Games"("id");



ALTER TABLE ONLY "public"."Tasks"
    ADD CONSTRAINT "Tasks_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "public"."Locations"("id");



ALTER TABLE ONLY "public"."Teams"
    ADD CONSTRAINT "Teams_teamAssignmentId_fkey" FOREIGN KEY ("teamAssignmentId") REFERENCES "public"."TeamAssignment"("id");



ALTER TABLE "public"."Games" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."HealingLedger" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Item" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ItemEffect" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Locations" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Shop" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Students" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Tasks" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."TasksLedger" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."TeamAssignment" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Teams" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."Games";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."Locations";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."Tasks";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."Teams";



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "anon";
GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "service_role";


















GRANT ALL ON TABLE "public"."Games" TO "anon";
GRANT ALL ON TABLE "public"."Games" TO "authenticated";
GRANT ALL ON TABLE "public"."Games" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Games_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Games_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Games_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."HealingLedger" TO "anon";
GRANT ALL ON TABLE "public"."HealingLedger" TO "authenticated";
GRANT ALL ON TABLE "public"."HealingLedger" TO "service_role";



GRANT ALL ON SEQUENCE "public"."HealingLedger_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."HealingLedger_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."HealingLedger_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Item" TO "anon";
GRANT ALL ON TABLE "public"."Item" TO "authenticated";
GRANT ALL ON TABLE "public"."Item" TO "service_role";



GRANT ALL ON TABLE "public"."ItemEffect" TO "anon";
GRANT ALL ON TABLE "public"."ItemEffect" TO "authenticated";
GRANT ALL ON TABLE "public"."ItemEffect" TO "service_role";



GRANT ALL ON SEQUENCE "public"."ItemEffect_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ItemEffect_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ItemEffect_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Item_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Item_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Item_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Locations" TO "anon";
GRANT ALL ON TABLE "public"."Locations" TO "authenticated";
GRANT ALL ON TABLE "public"."Locations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Locations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Locations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Locations_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Shop" TO "anon";
GRANT ALL ON TABLE "public"."Shop" TO "authenticated";
GRANT ALL ON TABLE "public"."Shop" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Shop_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Shop_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Shop_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Students" TO "anon";
GRANT ALL ON TABLE "public"."Students" TO "authenticated";
GRANT ALL ON TABLE "public"."Students" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Students_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Students_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Students_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Tasks" TO "anon";
GRANT ALL ON TABLE "public"."Tasks" TO "authenticated";
GRANT ALL ON TABLE "public"."Tasks" TO "service_role";



GRANT ALL ON TABLE "public"."TasksLedger" TO "anon";
GRANT ALL ON TABLE "public"."TasksLedger" TO "authenticated";
GRANT ALL ON TABLE "public"."TasksLedger" TO "service_role";



GRANT ALL ON SEQUENCE "public"."TasksLedger_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."TasksLedger_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."TasksLedger_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Tasks_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Tasks_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Tasks_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."TeamAssignment" TO "anon";
GRANT ALL ON TABLE "public"."TeamAssignment" TO "authenticated";
GRANT ALL ON TABLE "public"."TeamAssignment" TO "service_role";



GRANT ALL ON SEQUENCE "public"."TeamAssignment_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."TeamAssignment_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."TeamAssignment_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Teams" TO "anon";
GRANT ALL ON TABLE "public"."Teams" TO "authenticated";
GRANT ALL ON TABLE "public"."Teams" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Teams_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Teams_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Teams_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";



































drop extension if exists "pg_net";


