CREATE TABLE IF NOT EXISTS "public"."HealingTasks" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "text" text,
    "solution" text,
    "gameId" bigint
);

ALTER TABLE "public"."HealingTasks" OWNER TO "postgres";

ALTER TABLE ONLY "public"."HealingTasks"
    ADD CONSTRAINT "HealingTasks_gameId_fkey" FOREIGN KEY ("gameId") REFERENCES "public"."Games"("id");

ALTER TABLE "public"."HealingTasks" ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE "public"."HealingTasks" TO "anon";
GRANT ALL ON TABLE "public"."HealingTasks" TO "authenticated";
GRANT ALL ON TABLE "public"."HealingTasks" TO "service_role";

GRANT ALL ON SEQUENCE "public"."HealingTasks_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."HealingTasks_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."HealingTasks_id_seq" TO "service_role";

ALTER TABLE "public"."TasksLedger"
    ADD COLUMN IF NOT EXISTS "teamId" bigint;

ALTER TABLE ONLY "public"."TasksLedger"
    ADD CONSTRAINT "TasksLedger_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "public"."Teams"("id");

ALTER TABLE "public"."HealingLedger"
    RENAME COLUMN "taskId" TO "healingTaskId";

ALTER TABLE "public"."HealingLedger"
    RENAME COLUMN "healedTaskId" TO "healedTasksLedgerId";

ALTER TABLE "public"."HealingLedger"
    ADD COLUMN IF NOT EXISTS "teamId" bigint;

ALTER TABLE ONLY "public"."HealingLedger"
    DROP CONSTRAINT IF EXISTS "HealingLedger_taskId_fkey";

ALTER TABLE ONLY "public"."HealingLedger"
    DROP CONSTRAINT IF EXISTS "HealingLedger_healedTaskId_fkey";

ALTER TABLE ONLY "public"."HealingLedger"
    ADD CONSTRAINT "HealingLedger_healingTaskId_fkey" FOREIGN KEY ("healingTaskId") REFERENCES "public"."HealingTasks"("id");

ALTER TABLE ONLY "public"."HealingLedger"
    ADD CONSTRAINT "HealingLedger_healedTasksLedgerId_fkey" FOREIGN KEY ("healedTasksLedgerId") REFERENCES "public"."TasksLedger"("id");

ALTER TABLE ONLY "public"."HealingLedger"
    ADD CONSTRAINT "HealingLedger_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "public"."Teams"("id");

CREATE POLICY "Allow public team reads"
    ON "public"."Teams"
    FOR SELECT
    TO "anon", "authenticated"
    USING (true);

CREATE POLICY "Allow public task reads"
    ON "public"."Tasks"
    FOR SELECT
    TO "anon", "authenticated"
    USING (true);

CREATE POLICY "Allow public task ledger reads"
    ON "public"."TasksLedger"
    FOR SELECT
    TO "anon", "authenticated"
    USING (true);

CREATE POLICY "Allow public task ledger creation"
    ON "public"."TasksLedger"
    FOR INSERT
    TO "anon", "authenticated"
    WITH CHECK ("teamId" IS NOT NULL);

CREATE POLICY "Allow public healing task reads"
    ON "public"."HealingTasks"
    FOR SELECT
    TO "anon", "authenticated"
    USING (true);

CREATE POLICY "Allow public healing task creation"
    ON "public"."HealingTasks"
    FOR INSERT
    TO "anon", "authenticated"
    WITH CHECK ("gameId" IS NOT NULL);

CREATE POLICY "Allow public healing ledger reads"
    ON "public"."HealingLedger"
    FOR SELECT
    TO "anon", "authenticated"
    USING (true);

CREATE POLICY "Allow public healing ledger creation"
    ON "public"."HealingLedger"
    FOR INSERT
    TO "anon", "authenticated"
    WITH CHECK (
        "teamId" IS NOT NULL
        AND "healingTaskId" IS NOT NULL
        AND "healedTasksLedgerId" IS NOT NULL
    );
